### ISSUE TITLE
Clean secrets from config repos

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#104]
### Expected behavior

**Principles:**
- All shared/secrets/secrets.yml properties must be loaded in micro-depls/credhub and micro-depls/credhub-ha with micro-depls/credhub-seeder (this will check that required secrets are provided, for a given paas-templates version and iaas-type).

- Exception for some micro-depls deployments (powerdns, credhub-ha, credhub-seeder) that don't always have credhub available. So manifests should use spruce grab to get properties from shared/secrets/secrets.yml.

- Bosh deployments must leverage bosh director / config server / credhub to generate their own passwords and certificates. (default to /director-name/deployment-name/variable-name)

- Bosh deployments using outside properties / secrets should retrieve them with credhub
  * /secrets/... for global secrets (from shared/secrets/secrets.yml)
  * /tf/ for terraform generated (ie: net-id by terraform openstack in master-depls/terraform-config/openstack-hws/internet-network.tf)
  * /uaa for cloudfoundry uaa client secrets
 - /internalCA for internal plaform ca cert

- Concourse deployments can use some secrets in the concourse namespace (/concourse-name/team/variable names ). This credentials are copied from /secrets/ by micro-depls/concourse-credhub-seeder.

- Terraform spec should only retrieve credhub credentials / and use credhub terraform plugin to retrieve necessary credentials.

- Environment specific sizing/tuning of a bosh-deployment (if required) can be set in local <root-deployment/<deployment-name>/secrets/meta.yml.

### TODO
- [ ] delete all secrets.yml and meta.yml without any usefull properties
- [x] purge credhub "/cf" name space
- [ ] purge credhub "/secrets" name space
- [ ] relaunch micro-depls/credhub-seeder to clean up the credhub
- [ ] retrigger all terraform / bosh deployment in bosh / micro / master / ops / coab / kubo
- [x] fix legacy deployment not following principes
- [x] remove all deployment level secrets.yml
- [x] refactor and remove useless shared/secrets.yml (ie: openstack net-ids, broker password, bosh uuid )

**Comment by gberche-orange** [comment]
@poblin-orange relates/duplicates to #4 ?

**Comment by gberche-orange** [comment]
Related credhub issue to suggest support for metadata associated to credhub entries: https://github.com/cloudfoundry-incubator/credhub/issues/45

**Comment by poblin-orange** [comment]
reset has been applied for v42, identifying credhub /secrets stalled/missing entries
