### ISSUE TITLE
Design and prototype a credentials rotation mechanism

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#105]
### Expected behavior

As an operator, i expect the solution to provide tools to help rotate the credentials of the platform

* [ ] identify credentials which can be rotated without specific care/manual work
   * [ ] TLS certificates. 
      * [ ] Public TLS certs for intranet/internet traffic 
      * [ ] Internal TLs certs for control plane internal trafic. See inspiration in https://docs.pivotal.io/platform/2-8/security/pcf-infrastructure/certificate-types.html
         * See related #102 #84
   * [ ] db encryption keys
   * [ ] cf service accounts (incl coa)
   * [ ] concourse users (inc coa)
   * [ ] gitlab service accounts (inc coa, coab)
   * [ ] credhub users
   * [ ] UAA client id/client secret
   * [ ] service broker basic auth
      * [ ] client-facing osb-cmdb broker user auth. See https://github.com/orange-cloudfoundry/osb-cmdb-spike/issues/35
      * [ ] operator facing internal broker auth
* [x] automate handling credentials which require specific care such as #102 

### references
- https://credhub-api.cfapps.io/version/2.5/#_rotation_instructions

**Comment by gberche-orange** [comment]
related issues #102 #84

**Comment by poblin-orange** [comment]
manual rotation implemened fo v41 (delete credhub + let bosh regenerate, explicit internal CA double privosiionning on clients
bumped credhub 2.4 in v42. Generic mechanism to complete for v43

**Comment by poblin-orange** [comment]
TODO:
- [ ] bosh nats 
- [ ] cloudfoundry
- [ ] bosh dns (2020)

**Comment by gberche-orange** [comment]
As agreed with @poblin-orange , the issue content was edited to list the credentials to rotate. Would be useful to set associated security risks and priority.

**Comment by gberche-orange** [comment]
Reopening as #359 which closed this issue covered TLS certs rotation: this issue includes details for rotation of credentials with a wider scope
