### ISSUE TITLE
Kafka Strimizi service

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1089]
### Expected behavior

* As a paas-templates marketplace user
* In order to 
   * use kafka messaging features in my apps
   * use kafka db-like features in my apps
* I need 
  * a kafka service in the marketplace 

#### 1. Coab + cloud-service-broker as inner broker
 
* Use of COAB to provision a dedicated k3s cluster and install kafka within it using streamzi
* Pb: missing inner broker to control streamzi K8S CRs 
   * [ ] COAB can't yet leverage an inner broker with async provisionning: https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/364
   * [ ] Need COAB retries to join CSB #1117
* CSB brokepak options:
   * [ ] [terraform-provider-kubernetes-alpha](https://github.com/hashicorp/terraform-provider-kubernetes-alpha) ?
   * [ ] ~~[terraform-provider-kubernetes](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs) (see [GSA/eks-brokerpak](https://github.com/GSA/eks-brokerpak/blob/9b560683feb57bc6f5ef697c422987760817f77b/services/terraform/eks-bind.tf#L71-L75) example)~~: need CR support
   * [ ] [terraform-provider-helm](https://registry.terraform.io/providers/hashicorp/helm/latest/docs): 
      * [ ] with [a remote chart url syntax](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#example-usage---chart-url)
      * [ ] wait for all Strimzi CRs to be provisionned ?
         * [ ] [`helm --wait`](https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback) seems insufficient 
            * > --wait                         if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful. It will wait for as long as --timeout
            * [x] available [wait](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#wait) flag in terraform-provider
        * [ ] `helm --wait-for-jobs` with polling jobs
            * >  --wait-for-jobs                if set and --wait enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as --timeout
            * [ ] Clarify whether supported by terraform provider
               * [x] Submitted issue with code analysis https://github.com/hashicorp/terraform-provider-helm/issues/694
        * [ ] Craft a job to wait for Strimzi CR to be provionned and fail depending on its status
           * [ ] https://github.com/helm/helm/issues/9285 Helm and terraform-provider-helm possibly ignoring failed jobs and completing with success
      * depends on 
         * [ ] https://github.com/cloudfoundry-incubator/cloud-service-broker/issues/159 as [terraform-provider-helm](https://registry.terraform.io/providers/hashicorp/helm/latest/docs) states
            * > You should also have a local configured copy of kubectl.
         * ~~to use a [ Local Chart](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#example-usage---local-chart) https://github.com/cloudfoundry-incubator/cloud-service-broker/issues/114 to bundle the local chart~~

#### 2. Coab service instance + coab service binding

* [ ] https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/41 coab support for coa-based service bindings
   * [ ] May require fetching the Kafka user credentials from K8S secrets (instead of credhub)
      * [ ] Using coab K8S client
      * [ ] Using coab osb client, with an inner broker serving the K8S secret (if the secret path is predictable) ?

#### 3. Composite: coab and csb as leafs

See #1109

* leaf 1: Coab is configured with a noop inner broker (e.g. wordssimplest broker) since returned responses (dashboard and credentials) would be mostly ignored
* leaf 2: csb uses [cloudfoundry_service_instance](https://registry.terraform.io/providers/cloudfoundry-community/cloudfoundry/latest/docs/resources/service_instance) 
   * polls async service instance creation, configured with specific [tf operation-timeouts](https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts)
   * uses [depends_on](https://www.terraform.io/docs/language/meta-arguments/depends_on.html) if additional control is necessary

<details>
<summary>object diagram</summary>

![source](http://www.plantuml.com/plantuml/png/ZLR1RkCW4Btp5IWhzRAf57jlaNRL3ra9OKnIDXWim9MoQVwzE1I5P88pFJGsl3SUvZq6tdpWBao39iHs_wG8LFYE2JkCrgiWMUViGJhoQ91kgU63fB_fWUyE799onEk4TNjoytQDSH_a4JiceOmFt0X9VuWZDwGokQNvaQa-1bUREj9Bzw4oq2y0HyrDGerBAExuu2FenDVTMfpho9xxzyvoDqTSJKutzFEJnjzsLUV4Xo1d_EMXeIylQMY9qqild1g3icPc5gyD_NapswugLU-KwPNPbqK7Srlw_PHgr6rgEAXD1GYbgU2WCX1K22FM_LgUgq3XP2zDK5pFw5NnEYjKJi_r8cJaui3taexEVYYlh36oPzsHLGIXfyYXyGzKsiT8Sfww7xlk4hMvvSR0FZWr_5TCIxvhcTYnNBMq2sSu1bTyes4pFkt7Twc7N1jyA7f9ctbXHpdB4joK5dQxSDvTGZH5Y5od1Az2ihVJ1rdAFC4FltpA7HC1cB51i80pSQJIfZW6Q2OuLjbOzexlkE6NganEemBaBfD-CQc2BbCs6OnXWVGGYN80z2u-QDqKBPuCl87b0elKY7YdG3B2C6RI6aq6Pa4aZV5C-zqYSQqrjsvwklQOftscx6bLWrSFjmR90rP24e6DqBpIGcWIE1nHH71O5cyvOTJM1sf0C4QKjav7QOFYroN2qw5I22vEi0eVhrlAv4pEXDnTrLzVBRYiaBk115e-s1zGODPu9k8Aj9nG3FC7UQtfvQZjqTE_Xfi-_dTohtoGpXCC7xzGKhdDPmrWytk-Hlka4M8ogvOSXdkJffy6JRu0)

</details>

### Affected releases

* x.y
* earlier versions
