### ISSUE TITLE
Copy of shared-operators in gitops-fluxcd-repo is unbalanced, only performed in micro-depls/01-ci-k8s

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1415]
### Expected behavior

* As a paas-templates paas-templates author 
* In order to 
   * track updates made to `shared-operators` in gitops-fluxcd-repo while working on a k8s-config deployment
   * troubleshoot non propagating changes to `shared-operators` in gitops-fluxcd-repo 
* I need 
   * easily discover where copy of `shared-operators` in gitops-fluxcd-repo is performed
   * see copy of shared-operators in gitops-fluxcd-repo in each k8s config script

### Observed behavior
 
Only micro-depls/01-ci-k8s/k8s-config contains a `01-copy-shared-operators.sh` which symlinks shared-operators/k3s/fluxcd/coa-fluxcd-bridge/01-copy-shared-operators.sh

gitops-fluxcd-repo commit messages on `shared-operators` files include
```
set operator to debug log level

(cherry picked from commit 0b8c8008cbf5a7620bd74c1937210f6372699dcb) - COA manifests commit 9f97fa9043891bba0025701f9a945414cdda8aeb, on behalf of micro-depls/01-ci-k8s
```

Current `paas-templates-develop-wip-merged/micro-depls/01-ci-k8s/k8s-config/02-deploy.sh` content

```bash
#!/bin/bash

cd ${K8S_GIT_REPO_PATH}/shared-operators/k8s-kustomize-bases
git add .

cd ${K8S_GIT_REPO_PATH}/${COA_ROOT_DEPLOYMENT_NAME}/${COA_DEPLOYMENT_NAME}
git add .


CHANGE_DETECTED_COUNTER=$(git ls-files --others --exclude-standard  -d -c |wc -l )
if [ ${CHANGE_DETECTED_COUNTER} -gt 0 ]; then
  git commit --no-verify -a -m "${PAAS_TEMPLATES_COMMIT_MESSAGE} - COA manifests commit ${PAAS_TEMPLATES_COMMIT_ID}, on behalf of ${COA_ROOT_DEPLOYMENT_NAME}/${COA_DEPLOYMENT_NAME}"
  git --no-pager show HEAD
else
  echo "No change detected, skip commit"
fi
```

### Suggested fixes

* [ ] refine commit message wording into 
`COA manifests commit 9f97fa9043891bba0025701f9a945414cdda8aeb, performed from within micro-depls/01-ci-k8s through micro-depls/01-ci-k8s/k8s-config/02-deploy.sh`
i.e.
`  git commit --no-verify -a -m "${PAAS_TEMPLATES_COMMIT_MESSAGE} - COA manifests commit ${PAAS_TEMPLATES_COMMIT_ID}, performed from within ${COA_ROOT_DEPLOYMENT_NAME}/${COA_DEPLOYMENT_NAME}" through $0`
* [ ] add 01-copy-shared-operators.sh to each k8s/config repo
   * [ ] check race conditions among different paas-templates clones within different k8s-config pipelines
### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
on integration env, had race conditions when coa secrets bridge activated on multiple bosh deployments.
