### ISSUE TITLE
Manually edited Helm chart generated K8S map structure don't get reconciated by helm/flux, lacking procedure for operators/authors to rollback

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1419]
### Expected behavior

* As a paas-templates operator | paas-templates author 
* In order to 
   * quickly test changes without waiting for CI/CD cycles
   * test and commit final configuration
* I need 
   * a reliable way to revert manual configuration

### Observed behavior
 
* Following k9s-based of `kubectl edit of `a helm-managed ConfigMap with addition of a new key #1364 with new key such as `upstream-keepalive-timeout`
* The  fluxcd helm upgrade of the helmrease
* The newly live added map keys are not removed

### Root-cause analysis

When fluxcd helm controller reconciles a HelmRelease resource, the rendered K8S templates are applied using 3 way merge algorithm which has specific behavior with respect to existing "live state" (vs the desired "configuration" state in rendered template). In particular, this behavior depends on the content of the `kubectl.kubernetes.io/last-applied-configuration` annotation in live state, as well as the type of data updated (primitive, vs map or array). For a live entry in a map without being reflected in the  `kubectl.kubernetes.io/last-applied-configuration` annotation, the  way merge algorithm leaves the live entry unmodified.

The following references provide additional details on the helm behavior as well as k8s background on desired/live state and kubectl behavior during `kubectl apply` or `kubectl edit` commands

https://helm.sh/docs/faq/changes_since_helm2/#improved-upgrade-strategy-3-way-strategic-merge-patches

 In Helm 3, Helm generates a patch of the containers object between the old manifest, the live state, and the new manifest. It notices that the new manifest changes the image tag to 2.1.0, but live state contains a sidecar container.

https://github.com/helm/helm/issues/9547
>    To remove a value, you must provide a "null" value. i.e. command: [] or command: null. More information is provided in the FAQ.

The following blog summarizes the 3 way merge algorithm. Our case for the new `upstream-keepalive-timeout` key in the map, matches the `∅ (ignore)` case.

https://dev.to/derlin/helmfile-difference-between-sync-and-apply-helm-3-28o1
> The rules are (fields = key+value):
>     + (add) → new fields in the desired state not present in the old state are added (overwriting any live state)
>     ⌫ (remove) → fields existing in the old state that are not present in the desired state are removed (even if their value changed in the live state)
>     ± (overwrite) → fields in the live state that are also present in the desired state but have a different value are updated (whatever the old state)
>     ∅ (ignore) → the rest is left unchanged (e.g. new fields in the live state stay)

The following k8s documentation details the 3 way merge algorithm for a map field.  Our case for the new `upstream-keepalive-timeout` key in the map, matches  the last case `No | - | No | Do nothing. Keep live value.`

https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#merging-changes-to-map-fields

> Key in object configuration file | Key in live object configuration | Field in last-applied-configuration | Action
> -- | -- | -- | --
> Yes | Yes | - | Compare sub fields values.
> Yes | No | - | Set live to local configuration.
> No | - | Yes | Delete from live configuration.
> No | - | No | Do nothing. Keep live value.
> 

Kubectl edit by default does not update the `kubectl.kubernetes.io/last-applied-configuration` annotation. This can be opted in with `--save-config=true` flag

https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#kubectl-edit
    https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#edit
>          --save-config=false: If true, the configuration of current object will be saved in its annotation. Otherwise, the
>    annotation will be unchanged. This flag is useful when you want to perform kubectl apply on this object in the future.

### Possible workaround once a resource has been manually edited

* manually remove the added live keys + manually restart dependent resources (e.g. pods)
* manually delete the helmrelease using k9s and let fluxcd recreate it 
   * not applicable for helmrelease with persistent data

### Possible fixes to prevent the issue 

* ~~restrict resource edits to `kubectl edit --save-config=true`~~
   * not better: 
      * `kubectl.kubernetes.io/last-applied-configuration` is now consistent with data upon `kubectl edit`
      * however, upon flux reconciliation
         * manually edited fields still don't get removed 
         * helm values do get synced
         * `kubectl.kubernetes.io/last-applied-configuration`  does not get updated
   * instruct k9s to set the `--save-config=true` flag when editing a resource
      * ~configure kubectl defaults in .kube/config:~ preferences only supports colors and extensions
         * https://github.com/kubernetes/client-go/blob/6d69eb8ad66c8962b6ce2f610d46fa3ab7d23afb/tools/clientcmd/api/types.go#L28-L64
* [ ] prevent use of `kubectl edit` in bosh-cli
   * [ ] override default editor (vi) with a nice command explaining why edit is disabled in bosh cli: `KUBE_EDITOR="a-command-displaying-hint-and-return"`. See https://github.com/orange-cloudfoundry/orange-cf-bosh-cli/issues/81
   * [ ] investigate admission controller webhooks which would refuse PATCH/UPDATE from Manager=kubectl

### References

Somewhat related https://fluxcd.io/docs/faq/#how-to-patch-coredns-and-other-pre-installed-addons

> To patch a pre-installed addon like CoreDNS with customized content. Simply add a shell manifest with only the changed values and kustomize.toolkit.fluxcd.io/prune: disabled annotation into your git repository.

https://fluxcd.io/docs/components/kustomize/kustomization/#garbage-collection

> Garbage collection means that the Kubernetes objects that were previously applied on the cluster but are missing from the current source revision, are removed from cluster automatically.
> You can disable pruning for certain resources by either labeling or annotating them with:
> 
> kustomize.toolkit.fluxcd.io/prune: disabled
> 

### Affected releases

* 52.x
* earlier versions

**Comment by gberche-orange** [comment]
I also observe an HelmRelease object doesn't have its `kubectl.kubernetes.io/last-applied-configuration` annotation updated when it is changed (e.g. adding new values).

Tracking this down, this seems to be because kustomize controller uses server-side applies, and that `kubectl.kubernetes.io/last-applied-configuration` is then only updated when requested by a `kubectl` manager, whereas in the case of flux kustomize this is `kustomize-controller`

describe on the helmrelease:
```
┌───────────────────────────────────────────────────────────────────────────────── Describe(ingress-nginx/ingress-nginx) ──────────────────────────────────────────────────────────────────────────────────┐
│ Name:         ingress-nginx                                                                                                                                                                              │
│ Namespace:    ingress-nginx                                                                                                                                                                              │
│ Labels:       kustomize.toolkit.fluxcd.io/name=08-ingress-nginx                                                                                                                                          │
│               kustomize.toolkit.fluxcd.io/namespace=fluxcd                                                                                                                                               │
│ Annotations:  paas-templates-helm-source-url: https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx                                                                                 │
│               reconcile.fluxcd.io/requestedAt: 2021-11-24T13:42:13.451280423Z                                                                                                                            │
│ API Version:  helm.toolkit.fluxcd.io/v2beta1                                                                                                                                                             │
│ Kind:         HelmRelease                                                                                                                                                                                │
│ Metadata:                                                                                                                                                                                                │
[...]
│     Manager:      kustomize-controller                                                                                                                                                                   │
│     Operation:    Apply                                                                                                                                                                                  │
│     Time:         2021-11-24T14:01:35Z                                                                                                                                                                   │
│     API Version:  helm.toolkit.fluxcd.io/v2beta1                                                                                                                                                         │
│     Fields Type:  FieldsV1                                                                                                                                                                               │
```

related server-side last-applied logic during update
https://github.com/kubernetes/kubernetes/blob/c8c81cbfbb381129c904ed1ab387744946cf807a/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/lastappliedupdater.go#L48-L71

related kustomize controller setup of server-side manager
https://github.com/fluxcd/kustomize-controller/blob/2fa13ce887ee3878637202c0c55d0f1847ba262f/controllers/kustomization_controller.go#L377-L382

## background on server-side-applies

https://medium.com/swlh/break-down-kubernetes-server-side-apply-5d59f6a14e26

> LastAppliedUpdater will update the possible CSA lastapplied annotation. Of course, it is not required in SSA. But if your object was created by CSA and upgraded to SSA, you need to update this annotation when you perform SSA with kubectl.

https://kubernetes.io/docs/reference/using-api/server-side-apply/

>  Caution:
> 
> Keep the last-applied-configuration annotation up to date. The annotation infers client-side apply's managed fields. Any fields not managed by client-side apply raise conflicts.
> 
> For example, if you used kubectl scale to update the replicas field after client-side apply, then this field is not owned by client-side apply and creates conflicts on kubectl apply --server-side.
> 
> This behavior applies to server-side apply with the kubectl field manager. As an exception, you can opt-out of this behavior by specifying a different, non-default field manager, as seen in the following example. The default field manager for kubectl server-side apply is kubectl.
> 
> kubectl apply --server-side --field-manager=my-manager [--dry-run=server]
