### ISSUE TITLE
osb client platform check and tag propagation

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1537]
### Expected behavior

* As a paas-templates operator 
* In order to 
  * prevent client platform misconfiguration (target another client osb service broker) 
* I need
  * a consistency check of client platform on osbcmdb side
  * client platform id propagation (annotation/tags) 

### Observed behavior
 
x-osb-cmdb param indeed includes 
```yaml
      brokered_service_client_name: "cmdb-cf-z2-services"
      brokered_service_api_info_location: "api.redacted-domain.org/v2/info"
```

but they are not propagated as prometheus labels

+ osb-cmdb does not yet support rejecting requests based on api_info_location. Pending upstream issue to create. Potentially a crosscutting handling on all methods (e.g. a servlet filter or equivalent)

### Implementation steps

* [ ] Add support in osb-cmdb for rejecting based on api_info_location
* [ ] Add `brokered_service_client_name` ~~and  `brokered_service_api_info_location`~~ as prometheus metrics
   * [ ] set default value when missing in coab instances (pre-deploy.sh)
   * [ ] modify scrape config to include the metrics

### Affected releases

* x.y
* earlier versions

**Comment by gberche-orange** [comment]
@poblin-orange once osb-cmdb enforces the x-api-info-location header (say from cf_z2), then 
* related osb-cmdb smoke tests frpm master-depls/cf client would fail being rejected (x-api-info-location with value from api.master-depls-cf-system-domain/v2/info). This would require launching tests from osb client platform (similar to #932 )
* svcat smoke tests would fail (x-api-info-location with empty value): x-api-info-location enforcement should only be enabled on k8s client platforms.

Alternatives:
- disable some smoke tests phases osb-cmdb tests when x-api-info-location enforcement is turned on:  test_service_provisionning, ...., test_service_deprovisionning
- leave failing smoke tests
- configure smoke tests to use osb client platform. need to configure user/password/domain
- expand the feature to accept both the specified osb-client x-api-info-location and (implicitely without config) master-depls/cf x-api-info-location
