### ISSUE TITLE
Improve impact of alerting (epic)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1762]
### Expected behavior

* As a paas-templates operator | paas-templates maintainer
* In order to better leverage alerting signals
* I need to
   * handle alerts as 1st class observable objects (graph, stats, act...)
   * programmatically handle alerts
   * extend alert sources beyond metrics to:
      * logs
      * traces

### Observed behavior
 
* we only make use of prometheus-alert-manager whereas grafana alerting features can be a rich complement or a replacement
* existing alerts are misused and under-valued
  * existing alerts definition are lacking labelling

### Related issues

* https://github.com/orange-cloudfoundry/paas-templates/issues/1282

### Reference

* https://grafana.com/docs/grafana/latest/alerting/

> Grafana Alerting allows you to learn about problems in your systems moments after they occur. Create, manage, and take action on your alerts in a single, consolidated view, and improve your team’s ability to identify and resolve issues quickly.

* https://grafana.com/docs/grafana/latest/datasources/alertmanager/

> Grafana includes built-in support for Prometheus Alertmanager. Once you add it as a data source, you can use the [Grafana Alerting UI](https://grafana.com/docs/grafana/latest/alerting/) to manage silences, contact points as well as notification policies. A drop-down option in these pages allows you to switch between Grafana and any configured Alertmanager data sources.

* https://grafana.com/docs/grafana/latest/alerting/fundamentals/alertmanager/

> External Alertmanager
> 
> If you want to use a single alertmanager to receive all your Grafana, Loki, Mimir, and Prometheus alerts, you can set up Grafana to use an external Alertmanager. This external Alertmanager can be configured and administered from within Grafana itself.
> 
> Alertmanagers are visible from the drop-down menu on the Alerting Contact Points, Notification Policies, and Silences pages.
> 

* https://grafana.com/grafana/plugins/camptocamp-prometheus-alertmanager-datasource/
   * > This datasource lets you use the Alertmanager's API of Prometheus to create dashboards in Grafana.
   * https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource

### Affected releases

* x.y
* earlier versions

**Comment by JCL38-ORANGE** [comment]
https://github.com/grafana-operator/grafana-operator/issues/564

**Comment by gberche-orange** [comment]
Status as of June 2023
* [ ] https://github.com/grafana-operator/grafana-operator/issues/911
   * > Grafana alerting is a good feature in the UI but I think that APIs are not mature enough to work with third party software (like the operator).
* [ ] find and install helm chart supporting grafana alerting
   * [ ] https://artifacthub.io/packages/helm/grafana/grafana
      * > Provision alert rules, contact points, notification policies and notification templates. There are two methods to provision alerting configuration in Grafana. [...]
      * https://github.com/search?q=repo%3Agrafana%2Fhelm-charts+alerting&type=pullrequests
         * https://github.com/grafana/helm-charts/pull/1720
