### ISSUE TITLE
bastion hardening 

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1797]
### Expected behavior

* As a paas-templates operator | cf user | marketplace user | osb service provider | paas-templates author | paas-templates maintainer
* In order to 
* I need 

### todo

**Items that rescheduled for v56**
* [ ] Support proxy for remote access to k8s API. See https://github.com/orange-cloudfoundry/orange-cf-bosh-cli/issues/100
   * [ ] Tiny proxy with existing syntax
      * [ ] Official safe image
   * [ ] Squid
      * [ ] listen 8888
      * [ ] cache peer per FQDN
         * [ ] http://www.squid-cache.org/Doc/config/cache_peer_domain/
* [ ] Set bi-mode for using `sshpiper` pods and `docker-bosh-cli` bosh deployment at the same time  (let end users to move their content)
  * [ ] Wire `sshpiper` service on ops ip
  * [ ] Wire legacy `docker-bosh-cli` on osb ip
* [ ] Audit logs
   * [ ] Configure screen recording https://github.com/tg123/sshpiper#screening-recording
   * [ ] Set up log rotate

### Affected releases

* x.y
* earlier versions
