### ISSUE TITLE
Crossplane kuttl test result reports

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1808]
### Expected behavior

* As a paas-templates author | paas-templates maintainer
* In order to look at history of crossplane tests including kuttl junit-formatted reports
* I need to generate, store & publish a kuttl execution reports in HTML format

### Observed behavior
 
* Only kuttl pod outputs are currently available

### Possible approaches

* ArgoCD based job invocation could secure the job output
* Set up kuttl report generation/storage/publication in html format
	* [ ] set kuttl artifactsDir to point to mounted pvc	 
	* [ ] set kuttl reportName to either the 
	   * [ ] Pod name: kuttl-01-static-tests-manual-6c6-hwxzw
	   * [ ] JOb name: kuttl-01-static-tests-manual-6c6
	* [ ] How to dynamically set the reportName in mounted ConfigMap ?
	  * [ ] ytt reference for ytt controlled jobs
	  * [ ] bash script prior to execution of kuttl
	     * [ ] Looking up the pod name using downward api
	* [ ] Publish report in web ui
	   * https://github.com/inorton/junit2html
	   * https://github.com/web-innovate/bootstraped-multi-test-results-report
	      * https://github.com/web-innovate/bootstraped-multi-test-results-report/tree/master/junit-reporting-handlebars/src/main/resources/junit-reporting
		    * !! google analytics turned on by default

### Affected releases

* x.y
* earlier versions
