### ISSUE TITLE
Migrate kyverno helm charts to OCI repository

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1817]
### Expected behavior

* As a paas-templates operator 
* In order to 
   * stay aligned with the community
   * benefit from oci images caching
* I need 
   * to install kyverno from OCI registries

### Observed behavior

We're still using kyverno helm chart https repo which is still published to  https://kyverno.github.io/kyverno/index.yaml
* https://github.com/developer-guy/kyverno/blob/87a3a2dd5a12bd6c2fc844c863fcd836f8238fbf/.github/workflows/helm-release.yaml#L55-L60
```
curl https://kyverno.github.io/kyverno/index.yaml | grep 'created: "2022-12' | sort -r
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  181k  100  181k    0     0   569k      0 --:--:-- --:--:-- --:--:--  569k
    created: "2022-12-09T08:55:24.489915738Z"
    created: "2022-12-09T08:49:51.007111666Z"
    created: "2022-12-08T13:36:00.314647754Z"
    created: "2022-12-08T13:35:47.672091811Z"
    created: "2022-12-05T17:06:04.162322775Z"
```

* [ ] Requires using the Helm OCI Repository syntax https://fluxcd.io/flux/components/source/helmrepositories/#helm-oci-repository
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: default
spec:
  type: "oci"
  interval: 5m0s
  url: oci://ghcr.io/stefanprodan/charts
```
* [ ]  Renovate does not yet support Helm OCI Repositories
   * https://github.com/renovatebot/renovate/issues/18509
   * https://github.com/renovatebot/renovate/pull/19017
      * > This PR does not address HelmRepository OCI only OCIRepository

* [ ] helm-kubectl-boshrelease does not yet support a helm version >=3.8.0 with oci repository support https://github.com/orange-cloudfoundry/helm-kubectl-boshrelease/issues/29

### References

* https://kyverno.io/blog/2022/10/24/kyverno-1.8-released/#potentially-breaking-changes
> the Helm chart registry URL has changed to ghcr.io/kyverno/charts/kyverno so make sure to update your Helm repositories.
* https://github.com/kyverno/kyverno/pull/4479
* https://github.com/kyverno/kyverno/issues/4376

### Affected releases

* x.y
* earlier versions
