### ISSUE TITLE
NetworkPolicy support in MysqlInstance needs polishing

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1895]
### Expected behavior

* As a marketplace user 
* In order to use mysql on gcp
* I need the smoke tests to fully describe network policy contracts

### Observed behavior
 
* [ ] NetworkPolicy `cloudsql-egress-network-policy` is not [yet asserted](`gcp-depls/marketplace-k8s-consumer/k8s-config/manifests/75-crossplane-sample-xrcs-openstack-hws/ytt/config/kuttl-test-suite/10-dynamic-medium-mysql/11-check-network-policy.yaml`) at the spec level (only asserted as E2E test) 
* [ ] The minimal network policy to grant access to coreDNS should not be required to the app team team
   * [ ] Configure openshift to have this opened by default. 
      * [ ] Likely required redhat support
         * [x] https://access.redhat.com/solutions/5661901 `Pods are having issues with DNS after the network policies are applied` suggesting in 2020 to open ports to any destination on dns related ports
         * [ ] https://docs.openshift.com/container-platform/4.12/networking/dns-operator.html#nw-dns-operator_dns-operator DNS operator is running in namespace `openshift-dns-operator`. This should be used in the [egress to namespace-selector](https://kubernetes.io/docs/concepts/services-networking/network-policies/#behavior-of-to-and-from-selectors)
   * [ ] As a workaround, the network policy is provisionned by the composition
* [ ] The current [test fixture 08-allow-openshift-apps-egress-network-policy.yaml](`gcp-depls/marketplace-k8s-consumer/k8s-config/manifests/75-crossplane-sample-xrcs-openstack-hws/ytt/config/kuttl-test-suite/10-dynamic-medium-mysql/08-allow-openshift-apps-egress-network-policy.yaml`) has hard coded IP app domain. Should be injected from `local-configs-and-secrets`

/CC @pugetc

  ```yaml
  egress:
  # allow DNS resolution
  - ports:
    - port: 5353   <--
      protocol: UDP
    - port: 5353    <--
      protocol: TCP
```

### Affected releases

* x.y
* earlier versions
