### ISSUE TITLE
adapt to and leverage vibrant container image industry (incl docker-inc sunsets announcements)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1920]
### Expected behavior

* As a paas-templates operator |paas-templates author | paas-templates maintainer
* In order to optimize effort in face of container industry changes such as #1909 
* In order to efficiently leverage new container industry offers and opportunities
* I need paas-templates practices, architecture to embrace changes in OCI container build, serving

### Observed behavior

* [x] investments in private container hosting, including offline airgap https://github.com/orange-cloudfoundry/paas-templates/issues/20 (jcr/ harbor)
* [ ] investments in private container building 
* [ ] one-shot migrations of custom container image building from dockerhub to gh actions
* [ ] in place process to leverage GCP cloud build infrastructure and the current industry wide effort around `Supply chain Levels for Software Artifacts, or SLSA (salsa)` https://slsa.dev/ https://slsa.dev/spec/v0.1/levels#summary-of-levels
 
### Affected releases

* x.y
* earlier versions
