### ISSUE TITLE
Renovate jobs polluting warning related private orange helm repo

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1981]
### Expected behavior

* As a paas-templates maintainer
* In order to avoid performing diagnostics for known issues/limitations
* I need to avoid polluting traces in renovate output 

### Observed behavior
 
```
DEBUG: Datasource connection error
{  "baseBranch": "feature-bumps",  "datasource": "helm",  "packageName": "s3-operator",  "errCode": "ERR_INVALID_URL" }
DEBUG: Failed to look up helm package s3-operator (s3-operator)(packageFile="gcp-depls/marketplace-k8s-consumer/k8s-config/manifests/80-s3-operator/s3-operator-helm-release.yaml", dependency="s3-operator")
{  "baseBranch": "feature-bumps" }
```

gcp-depls/marketplace-k8s-consumer/k8s-config/manifests/80-s3-operator/diod-marketplace-unstable-helm-repo.yaml

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: diod-marketplace-unstable-repo
  namespace: fluxcd # by convention (although not leveraged yet by an future hosted renovate version)
spec:
  interval: 10m
  url: ${external_diod_marketplace_unstable_repo_url}
```

### Possible fixes

* [ ] Find a way to exclude this dependency from renovate scan
* [ ] Renovate from intranet 
   * [ ] In paas-templates 
      * [ ] helm chart
   * [ ] In gitlab

### Affected releases

* x.y
* earlier versions

**Comment by gberche-orange** [comment]
closing as duplicate of #1997 which has more details
