### ISSUE TITLE
renovate error on corp private helm repos 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1997]
### Expected behavior

* As a paas-templates maintainer
* In order to 
* I need to reduce number of false alerts from renovate

### Observed behavior
 
Failure to bump corporate dependencies:
* orange-mariadb
* observability
* openshift helm installations:
   * s3 operator

Renovate failed to look up the following dependencies: Failed to look up helm package s3-operator, Failed to look up helm package orange-mariadb.

Files affected: gcp-depls/marketplace-k8s-consumer/k8s-config/manifests/80-s3-operator/s3-operator-helm-release.yaml, shared-operators/k8s-kustomize-bases/helm/orange-mariadb/orange-mariadb-helm-release.yaml

```
DEBUG: No host on ${external_diod_marketplace_unstable_repo_url}/index.yaml
{
  "baseBranch": "feature-bumps"
}

DEBUG: No host on ${external_diod_marketplace_unstable_repo_url}/index.yaml
{
  "baseBranch": "feature-bumps"
}

DEBUG: Datasource connection error
{
  "baseBranch": "feature-bumps"
  "datasource": "helm"
  "packageName": "s3-operator"
  "errCode": "ERR_INVALID_URL"
}

DEBUG: Failed to look up helm package s3-operator
{
  "baseBranch": "feature-bumps"
  "dependency": "s3-operator"
  "packageFile": "gcp-depls/marketplace-k8s-consumer/k8s-config/manifests/80-s3-operator/s3-operator-helm-release.yaml"
}
```

### Possible fixes

* [ ] exclude the files from renovate (fragile to file renaming): ignorePath
* [x] exclude the dependency `s3-operator`: ignoreDep
* [ ] configure mend renovate with access to corporate private helm repo
   * https://docs.renovatebot.com/getting-started/private-packages/
* [ ] configure a self hosted renovate instance within the corporate network, running in gitlab https://gitlab.com/to-be-continuous/tools/renovate

### Affected releases

* x.y
* earlier versions

**Comment by gberche-orange** [comment]
reopening after post-standup since impact is a bit larger.
