### ISSUE TITLE
Progressive adoption of longhorn

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2011]
### Expected behavior

As a paas-templates maintainer,
* In order to be relevant when expressing requirements for K8S storage classes
* I need to grow skills related to software-defined-storage with hands on feedback on longhorn

As a paas-templates maintainer,
* In order to get flexible, feature-rich options related to storage
* I need get feedback from longhorn progressive deployment with production workloads while mitigating risks

### Observed behavior
 
* Longhorn 1.4 storage classes used with
   * open-ldap (mostly-read volumes)
   * bastion ssh-pipper home directories (read, low write activity)

* Identified risks with longhorn adoption for data services, with longhorn being installed within paas-templates K8S cluster running on VMs with regular upgrade cycles and sometimes vmware-infrastructure triggered outage/live-migrations

### Possible approach

* [ ] get production feedback on control plane elements with low risks of critical data loss
   * [ ] gitlab as part of #2004

* [ ] Run tests to assess data consistency of longhorn volumes in presence of regular maintenance and infrastructure outages
   * [ ] fio consistency checks https://fio.readthedocs.io/en/latest/fio_doc.html#verification
      * > If writing to a file, fio can verify the file contents after each iteration of the job. Each verification method also implies verification of special header, which is written to the beginning of each block. This header also includes meta information, like offset of the block, block number, timestamp when block was written, etc. verify can be combined with verify_pattern option. The allowed values are: md5... 
      * > This option can be used for repeated burn-in tests of a system to make sure that the written data is also correctly read back. If the data direction given is a read or random read, fio will assume that it should verify a previously written file. If the data direction includes any form of write, the verify will be of the newly written data. To avoid false verification errors, do not use the norandommap option when verifying data with async I/O engines and I/O depths > 1. Or use the norandommap and the lfsr random generator together to avoid writing to the same offset with multiple outstanding I/Os.
      * https://github.com/axboe/fio/tree/master/examples exmaple fio configs
      * [ ] likely leveraging kube-str https://kubestr.io/ 
         * https://kubestr.io/fio/ example fio files (coming)
         * https://asciinema.org/a/D9EFwlEUVx787hayFapdHljBW sample fio kube-str UX
         * [ ] Check content of `default-fio` when not specifying a fio file to make sure it runs verifications
   * [ ] possibly simulate infrastructure outage with chaos engineering

* [ ] Measure service performance impact of using replicated volumes for data services serving write traffic patterns (e.g. how is latency of write statements in mysql galera cluster impacted by longhorn synchronous across az replication)
* [ ] Measure service availability impacts of replicated volumes for data services (i.e. how well is galera cluster behaving with pods [being killed by longhorn during volume maintenance](https://longhorn.io/docs/1.4.2/high-availability/recover-volume/))
* [ ] Detail with of our stateful data services are suiteable for infrastructure level migrations (i.e. whose pods can be rescheduled on different az with customer clients transparently reconnecting #458 )
   * [ ] mysql galera cluster
   * [ ] mongodb
   * [ ] rabbitmq
   * [ ] redis

* [ ] Evaluate how longhorn 1.5 (#1998)  (which embeds new SPDK https://spdk.io/ data plane engine) improves

* [ ] Test data migration with a series of manual steps and no load
   * > Storage classes are immutable
   * use of tags to restrict scheduling on certain nodes
   * use of [`replica autobalance` policy](https://longhorn.io/docs/1.4.2/high-availability/auto-balance-replicas/)
* [ ] Verify noisy neighbors properties of longhorn replicas
* [ ] To optimize latency, investigate usage of underlying infrastructure storage class without replication (to avoid two levels of replication)

#### Longhorn

* https://longhorn.io/docs/1.4.2/concepts/#1-design
   * > If the current healthy replica count is more than the specified replica count, Longhorn will do nothing. In this situation, if a replica fails or is deleted, Longhorn won’t start rebuilding new replicas unless the healthy replica count dips below the specified replica count.
* https://longhorn.io/docs/1.4.2/concepts/#232-how-new-replicas-are-added
   * > The following steps show a more detailed breakdown of how Longhorn adds new replicas:  1. The Longhorn Engine is paused.  2. Let’s say that the chain of snapshots within the replica consists of the live data and a snapshot. When the new replica is created, the live data becomes the newest (second) snapshot and a new, blank version of live data is created.      3. The new replica is created in WO (write-only) mode.    4. The Longhorn Engine is unpaused.   5. All the snapshots are synced.  6. The new replica is set to RW (read-write) mode.
* https://longhorn.io/docs/1.4.2/concepts/#245-crash-consistency
   * >Longhorn is a crash-consistent block storage solution. It’s normal for the OS to keep content in the cache before writing into the block layer. [...] Longhorn runs the sync command automatically before creating a snapshot.
* https://longhorn.io/docs/1.4.2/best-practices/#deploying-workloads
* > If you’re using ext4 as the filesystem of the volume, we recommend adding a liveness check to workloads to help automatically recover from a network-caused interruption, a node reboot, or a Docker restart. See [this section](https://longhorn.io/docs/1.4.2/high-availability/recover-volume/) for details.
   * https://longhorn.io/docs/1.4.2/high-availability/recover-volume/
      * > When an unexpected detachment happens, which can happen during a [Kubernetes upgrade](https://github.com/longhorn/longhorn/issues/703), a [Docker reboot](https://github.com/longhorn/longhorn/issues/686), or a network disconnection, Longhorn automatically deletes the workload pod if the pod is managed by a controller (e.g. deployment, statefulset, daemonset, etc…). By deleting the pod, its controller restarts the pod and Kubernetes handles volume reattachment and remount.
* https://longhorn.io/docs/1.4.2/best-practices/#volume-maintenance
   * > We highly recommend using the built-in backup feature of Longhorn. For each volume, schedule at least one recurring backup. If you must run Longhorn in production without a backupstore, then schedule at least one recurring snapshot for each volume.
* https://longhorn.io/docs/1.4.2/volumes-and-nodes/scheduling/#scheduling-policy
   * > Longhorn schedules replicas based on multiple factors. [...] First, Longhorn will always try to schedule the new replica on a new node with a new zone if possible. [...] If any tag has been set in order to be selected for scheduling, the node tag and the disk tag have to match when the node or the disk is selected.
* https://longhorn.io/docs/1.4.2/volumes-and-nodes/storage-tags/
* https://longhorn.io/docs/1.4.2/high-availability/data-locality/
* https://longhorn.io/docs/1.4.2/volumes-and-nodes/maintenance/ Node Maintenance and Kubernetes Upgrade Guide
* https://longhorn.io/docs/1.4.2/high-availability/auto-balance-replicas/
   * > When replicas are scheduled unevenly on nodes or zones, Longhorn `Replica Auto Balance` setting enables the replicas for automatic balancing when a new node is available to the cluster. [...] Longhorn supports setting individual volume for `Replica Auto Balance`. [...] You can change the Replica Auto Balance setting for individual volume after creation on the volume detail page, or do multiple updates on the listed volume page.
* Better understand data durability in face of vm loss (Linux os cache is only documented as [being flushed/synced by longhorn when creating snapshot](https://longhorn.io/docs/1.4.2/concepts/#245-crash-consistency))

https://www.replicated.com/blog/why-replicated-has-moved-away-from-recommending-longhorn-for-kurl-storage
> Why Replicated has moved away from recommending Longhorn for kURL storage
>  Feb 21, 2023
> [...]
> Our new default recommendation is OpenEBS local-pv for local storage, and Rook for distributed storage, with Rook requiring dedicated block devices. 

#### Rook

https://rook.io/docs/rook/v1.11/Getting-Started/example-configurations/#block-devices

#### Multiple VSAN storage controllers ?

One per vsan cluster

### Affected releases

* x.y
* earlier versions
