### ISSUE TITLE
Intranet egress metallb troubleshooting checklist

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2074]
### Expected behavior

* As a paas-templates operator
* In order to troubleshoot intranet ingress related to metallb
* I need some checklist and documentation of expected behavior

### Observed behavior

This issue aims at collecting some diagnostics steps.

#### how things work in v56 with normal operations on vmware environment

Metallb is used in l2 mode to announce virtual IPs for both intranet facing traffic and paas-templates internal traffic.

Given metallb is properly starting without error 

```
metallb controller logs

{"branch":"v0.12.1","caller":"level.go:63","commit":"dbe1a20","goversion":"gc / go1.18.1 / amd64","level":"info","msg":"MetalLB controller starting version 0.12.1 (commit dbe1a20, branch v0.12.1)","ts":"2023-09-
15T08:54:39.107767616Z","version":"0.12.1"}                                                                                                                                                                        
{"caller":"level.go:63","configmap":"metallb-system/config-metallb","event":"configLoaded","level":"info","msg":"config (re)loaded","ts":"2023-09-15T08:54:39.237347774Z"}                                         
{"caller":"level.go:63","event":"stateSynced","level":"info","msg":"controller synced, can allocate IPs now","ts":"2023-09-15T08:54:39.244042118Z"}                                                                
  
```

Given a kubernetes resource (usually a Service) is annotated with metallb annotation `metallb.universe.tf/address-pool: ops-public-vip-pool` as follows

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: ops-public-vip-pool
  labels:
    app.kubernetes.io/instance: traefik-traefik
  name: traefik-public-ops-lb

spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: bastion-ssh
    port: 80
    protocol: TCP
    targetPort: bastion-ssh

  - name: websecure
    port: 443
    protocol: TCP
    targetPort: websecure

  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
```

Given the service has some backend endpoints to send the traffic, usually identified by the selector

https://kubernetes.io/docs/concepts/services-networking/service/#endpoints
> The set of Pods targeted by a Service is usually determined by a [selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) that you define.
> In the Kubernetes API, an [Endpoints](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/endpoints-v1/) (the resource kind is plural) defines a list of network endpoints, typically referenced by a Service to define which Pods the traffic can be sent to.

```
──────────────────────────────────────────────────────────────────────────────── Describe(traefik/traefik-public-ops-lb) ─────┐
│ Name:                     traefik-public-ops-lb                                                                             │
│ Namespace:                traefik                                                                                           │
[..]
│ Selector:                 app.kubernetes.io/instance=traefik,app.kubernetes.io/name=traefik                                 │
│ Type:                     LoadBalancer                                                                                      │
│ IP Family Policy:         SingleStack                                                                                       │
│ IP Families:              IPv4                                                                                              │
│ IP:                       10.43.201.33                                                                                      │
│ IPs:                      10.43.201.33                                                                                      │
│ LoadBalancer Ingress:     10.x.y.z2.152                                                                                     │
│ Port:                     bastion-ssh  80/TCP                                                                               │
│ TargetPort:               bastion-ssh/TCP                                                                                   │
│ NodePort:                 bastion-ssh  30418/TCP                                                                            │
│ Endpoints:                10.42.1.236:9090,10.42.2.219:9090,10.42.3.153:9090                                                │
```

Then metallb controller assign an k8s node from the annotated addresspool

```
metallb-controller-6fbfb96c47-rwcvw {"caller":"level.go:63","event":"startUpdate","level":"debug","msg":"start of service update","service":"traefik/traefik-public-ops-lb","ts":"2023-09-18T13:46:30.481692717Z"}
metallb-controller-6fbfb96c47-rwcvw {"caller":"level.go:63","event":"ipAllocated","ip":["10.x.y.z"],"level":"info","msg":"IP address assigned by controller","service":"traefik/traefik-public-ops-lb","ts":"2023-09-18T13:46:30.481809643Z"}
metallb-controller-6fbfb96c47-rwcvw {"caller":"level.go:63","event":"serviceUpdated","level":"info","msg":"updated service object","service":"traefik/traefik-public-ops-lb","ts":"2023-09-18T13:46:30.511617188Z"}
 
```

Then the speakers will announce this assigned IP address through gratuitous ARPs, and respond to ARP requests.

```
metallb-speaker-kv6rf {"caller":"level.go:63","event":"serviceAnnounced","ips":["10.x.y.z"],"level":"info","msg":"service has IP, announcing","pool":"ops-public-vip-pool","protocol":"layer2","service":"traefik/traefik-public-ops-lb","ts":"2023-09-15T10:16:05.070599211Z"}
```

This can also be observed with the following two commands:

Arping sends an ARP Probe request https://en.wikipedia.org/wiki/Address_Resolution_Protocol#ARP_probe on the network. Metallb speakers in any of the k8s nodes (in the same L2 network) are responding with an ARP response, containing their mac address

```
agents/650ebbfa-efda-4ceb-9c8d-497ac29bc2a5:~# arping 10.x.y.z 
ARPING 10.x.y.z from 10.a.b.c eth1
Unicast reply from 10.x.y.z [00:50:56:A0:4D:5D]  0.616ms
```

Also the ARP probe requests and responses can be captured using tcpdump on the nodes

```
agents/6f76da76-6014-453b-bb2e-fe107500aa95:~# tcpdump -i eth1 -e -n  arp 
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth1, link-type EN10MB (Ethernet), capture size 262144 bytes
13:38:29.469272 00:50:56:a0:bc:10 > 00:50:56:a0:f5:2c, ethertype ARP (0x0806), length 60: Request who-has 10.x.y.z (00:50:56:a0:f5:2c) tell 10.a.b.c, length 46
13:38:29.469387 00:50:56:a0:f5:2c > 00:50:56:a0:bc:10, ethertype ARP (0x0806), length 60: Reply 10.x.y.z is-at 00:50:56:a0:f5:2c, length 46
```

Note that ARP responses are currently performed on all nics (both intranet-facing and internal 192.168 nic). See https://github.com/metallb/metallb/pull/1536

`arp` command dumps the local ARP table. The ARP table first needs to be populated for the vip, e.g. initiating traffic to the vip. When called on a k8s node in the same L2 network, we can obtain previously announced VIPs, their associated MAC, and sometimes their DNS names associated to their internal private IP addresses, easing their identification

```
# trigger traffic to get arp tables filled in, even if we don't get icmp responses 
agents/650ebbfa-efda-4ceb-9c8d-497ac29bc2a5:~# ping 10.x.y.z 443
PING 443 (0.0.1.187) 56(124) bytes of data.
^C
--- 443 ping statistics ---

# note: nc was usually insufficient to getr arp table filled in. Not yet clear why
agents/650ebbfa-efda-4ceb-9c8d-497ac29bc2a5:~# nc -vz 10.x.y.z 443
Connection to 10.x.y.z 443 port [tcp/https] succeeded!

agents/650ebbfa-efda-4ceb-9c8d-497ac29bc2a5:~# arp --help
Usage:
  arp [-vn]  [<HW>] [-i <if>] [-a] [<hostname>]             <-Display ARP cache
  arp [-v]          [-i <if>] -d  <host> [pub]               <-Delete ARP entry
  arp [-vnD] [<HW>] [-i <if>] -f  [<filename>]            <-Add entry from file
  arp [-v]   [<HW>] [-i <if>] -s  <host> <hwaddr> [temp]            <-Add entry
  arp [-v]   [<HW>] [-i <if>] -Ds <host> <if> [netmask <nm>] pub          <-''-

        -a                       display (all) hosts in alternative (BSD) style
        -e                       display (all) hosts in default (Linux) style
        -s, --set                set a new ARP entry
        -d, --delete             delete a specified entry
        -v, --verbose            be verbose
        -n, --numeric            don't resolve names
        -i, --device             specify network interface (e.g. eth0)
        -D, --use-device         read <hwaddr> from given device
        -A, -p, --protocol       specify protocol family
        -f, --file               read new entries from file or from /etc/ethers

agents/650ebbfa-efda-4ceb-9c8d-497ac29bc2a5:~# arp -n | grep 10.x.y.z
10.x.y.z            ether   00:50:56:a0:4d:5d   C                     eth1

# Example of internal VIPs being announced
agents/650ebbfa-efda-4ceb-9c8d-497ac29bc2a5:~# arp -n | head
Address                  HWtype  HWaddress           Flags Mask            Iface
[...]
192.168.116.208          ether   00:50:56:a0:b8:28   C                     eth0
[...]

# -A option provides the full reverse dns, which may be handy as times to avoid going to local DNS caches
agents/650ebbfa-efda-4ceb-9c8d-497ac29bc2a5:~# arp -a | less 
534d1a04-3caa-46a5-81ad-c030b0302aec.agents.net-bosh-2.00-core-connectivity-k8s.bosh (192.168.116.226) at 00:50:56:a0:fc:7b [ether] on eth0

agents/650ebbfa-efda-4ceb-9c8d-497ac29bc2a5:~# arp -a | grep 10.x.y.z
redacted-geographic-fqdn.org (10.x.y.z) at 00:50:56:a0:4d:5d [ether] on eth1

guillaume@guillaume-dev-box:~$ host  ops-portal.redacted-ops-domain.org
ops-portal.redacted-ops-domain.org is an alias for redacted-functional-fqdn.org.
redacted-functional-fqdn.org is an alias for redacted-geographic-fqdn.org.
redacted-geographic-fqdn.org has address 10.x.y.z
```

To identify a vmware vm from its mac address, you may use the following govc script, thanks to https://github.com/vmware/govmomi/issues/1201#issuecomment-417988520

```
log-govc # use secrets.bosh_credhub_secrets in shared/secrets.yaml
M=$(echo 00:50:56:a0:4d:5d | tr [:upper:] [:lower:] )
govc object.collect -json -type m / config.hardware.device | jq -r '. | select(.ChangeSet[].Val.VirtualDevice[].MacAddress == "'$M'") | [.Obj.Type, .Obj.Value] | join(":")' | xargs govc ls -L
/[...]/vm/SERVICES/Integration/vms/78cf0582-cac9-49a2-b02e-2d793f8180fa/vm-9dc2a0c4-1758-44b2-8a62-bbea891f7d8a

govc object.collect -json -type m / config.hardware.device | jq -r '. | select(.ChangeSet[].Val.VirtualDevice[].MacAddress == "'$M'") | [.Obj.Type, .Obj.Value] | join(":")' | xargs govc ls -L | xargs -I {} -n 1  govc vm.info -vm.ipath={} | grep 'IP address:' | awk '{print $3}' | xargs -n 1 get-vm-info.sh 

>vm properties...
bosh director   : micro-bosh
bosh deployment : 00-core-connectivity-k8s
bosh instance   : agents/650ebbfa-efda-4ceb-9c8d-497ac29bc2a5
bosh created    : 2023-09-15T16:45:38Z

vm name         : vm-17887ce9-7bd7-4120-a0a4-3e466ddcc7cb
vm host         : [...]
```

The bosh index (`agents/0` in this case) is then obtained from bosh deployment inventory
```
$ bosh is --details | grep 650ebbfa
agents/650ebbfa-efda-4ceb-9c8d-497ac29bc2a5             running z1      192.168.116.225 00-core-connectivity-k8s        started         vm-17887ce9-7bd7-4120-a0a4-3e466ddcc7cb 4cpu-16g        disk-a64545aa-5929-4430-ad77-9ce0c1065240  6fba5de5-d3f7-47e9-8b73-0a54b1313107    0       true    false
```

As a result, a k8s node is receiving traffic addressed to the vip from the vmwar nsxt router

This can be observed using tcpdump on the node, e.g. for http traffic. Unfortunately, for intranet traffic the source ip address is not preserved.

Kube-proxy component is then receiving the request and forwarding it to the destination endpoints adresses (usually pods)

in v56 in core-connectivity, kube-proxy is implemented using LVS (linux virtual server), consequently this can be observed as iptables from the service cluster ip (10.43.* by default in k3s)

```
clusterIP=$(kubectl get services/traefik-public-ops-lb -n traefik -o json | jq -r .spec.clusterIP)
 
bosh ssh agents/0 -c "sudo iptables-save | grep ${clusterIP}"
[...]
 -A KUBE-SERVICES -d 10.43.201.33/32 -p tcp -m comment --comment "traefik/traefik-public-ops-lb:bastion-ssh cluster IP" -j KUBE-SVC-YXDJKGHQPQHFAP2D
 -A KUBE-SERVICES -d 10.43.201.33/32 -p tcp -m comment --comment "traefik/traefik-public-ops-lb:websecure cluster IP" -j KUBE-SVC-YJSOUWKLSM24ZEYZ
[...]
```

The above line, adds a new rule to add the cidr `10.43.201.33/32` into the chain. Further analysis of the kube proxy iptables is out of the scope of this issue.

#### troubleshooting check list

This section is mostly an adaptation of troubleshooting documentation available at https://metallb.universe.tf/troubleshooting/ with examples adapted to paas-templates context

* [ ] Check metallb lb installation is properly started and no error messages
* [ ] Check the resources annotated with metallb annotations are correct
    * [ ] The adresspool cidr is consistent with the corresponding K8s nodes cidr, see https://github.com/orange-cloudfoundry/paas-templates/issues/1922
* [ ] Check that the services have proper backing endpoints associated
    * Using popeye
        * From K9s :popeye command
        * From popeye  cli
```
    Errors:

    (POP-1100) No pods match service selector
    (POP-1105) No associated endpoints

    Warnings:

    (POP-1109) Only one Pod associated with this endpoint
    (POP-1200) No pods match Ingress pod selector
    (POP-1201) No namespaces match Ingress namespace selector
```
* Using kubectl:
   ```
    $ kubectl get pods --selector=app.kubernetes.io/name=traefik --selector=app.kubernetes.io/instance=traefik-traefik -A
    No resources found
   ```
* [ ] If not, understand why the target endpoints (usually pod workloads) are missing:
    * [ ] Invalid selector
    * [ ] Pod missing/down/failing
* [ ] Check gratuitous arp packet are properly transmitted to routers
    * [ ] On openstack https://github.com/orange-cloudfoundry/paas-templates/issues/1161 https://github.com/orange-cloudfoundry/paas-templates/issues/1133
    * [ ] On vmware, nsxt firewall related ARP controls
* [ ] Check nxst router are properly routing the announced VIP (e.g. compare all VIPS, environment instances to infer a possible outage in the NSX infrastructure or upstream network infrastructure) 

### Affected releases

* x.y
* earlier versions
