### ISSUE TITLE
Improve observability of k8s servers control planes

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2093]
### Expected behavior

* As a paas-templates operator
* In order to ensure good SLO on workloads running in k8s servers
* I need good observability of k8s control planes

### Observed behavior

Existing k8s-system-api-server dashboard with some panels displaying some metrics including apiserver_request_duration_seconds  and apiserver_request_total
https://github.com/orange-cloudfoundry/paas-templates-private/blob/6937d20db22c41fca4e2364e4a2054a93aa168a5/shared-operators/k8s-kustomize-bases/grafana-dashboards/k8s/k8s-system-api-server.json

![image](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/e14c9bb2-6be5-4fa3-abd1-9561e8f7ec48)

### Possible improvements 

 * [ ] TCP offload observability https://github.com/orange-cloudfoundry/paas-templates/issues/2086
 * [ ] Observability of k8s api server see https://kubernetes.io/docs/reference/instrumentation/metrics/ 
    * [ ] Scraping all k8s api clusters https://github.com/orange-cloudfoundry/paas-templates/issues/2092
    * [ ] k8s api dashboards
       * [ ] k8s-control-plane.libsonnet dashboard https://github.com/prometheus-operator/kube-prometheus/commits/8ce7838d24537a276a684da3f1fe5ffc08bfd495/jsonnet/kube-prometheus/components/k8s-control-plane.libsonnet
          * https://prometheus-operator.dev/docs/kube/developing-prometheus-rules-and-grafana-dashboards/
             > kube-prometheus ships with a set of default [Prometheus rules](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/) and [Grafana](http://grafana.com/) dashboards. At some point one might like to extend them, the purpose of this document is to explain how to do this.
            > All manifests of kube-prometheus are generated using [jsonnet](https://jsonnet.org/). Prometheus rules and Grafana dashboards in specific follow the [Prometheus Monitoring Mixins proposal](https://github.com/monitoring-mixins/docs/blob/master/design.pdf)
          * flux jsonnet controller contrib is unmaintained https://github.com/pelotech/jsonnet-controller/issues/45#issuecomment-1468672343
          * TBC whether jsonnet rendering is built-in into the kube-prometheus operator

       * [ ] Openshift kube-apiserver-operator api_performance_dashboard and recording rules
          * [ ] https://github.com/openshift/cluster-kube-apiserver-operator/blob/a66fe80f9ce087436b7bdd2e05af512892864664/manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
          * [ ] https://github.com/openshift/cluster-kube-apiserver-operator/blob/a66fe80f9ce087436b7bdd2e05af512892864664/manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml recording rules
    * [ ] k8s api alerts
       * [ ] As Pyrra error budgets
          * https://github.com/pyrra-dev/pyrra
          * https://github.com/prometheus-operator/kube-prometheus/pull/1667
          * [ ] KubeAPIErrorBudgetBurn https://github.com/prometheus-operator/runbooks/blob/f8061f3e9b3337d90107aa2f10a0111f3f6dc86f/content/runbooks/kubernetes/KubeAPIErrorBudgetBurn.md
       * [ ] KubeAPIDown https://github.com/prometheus-operator/runbooks/blob/f8061f3e9b3337d90107aa2f10a0111f3f6dc86f/content/runbooks/kubernetes/KubeAPIDown.md

 * [ ] Observability of k8s api databases:
    * [ ] By clusters
       * [ ] 00-shared-services https://github.com/orange-cloudfoundry/paas-templates/issues/2064
       * [ ] 00-core-connectivity-k8s
       * [ ] 00-supervision
       * [ ] 00-marketplace
    * [ ] Slow queries alerts
    * [ ] Database size
    * [ ] Conservative alerting on database capacity
       * [ ] load average
       * [ ] disk space
 * [ ] Observability of k8s inventory (through prometheus ?)
    * [ ] Total number of resources
    * [ ] Number of resources per categories

### Reference

* https://kubernetes.io/docs/reference/instrumentation/metrics/ 
> apiserver_storage_objects: Number of stored objects at the time of last check split by kind.
>   apiserver_request_total: Counter of apiserver requests broken out for each verb, dry run value, group, version, resource, scope, component, and HTTP response code.
>   apiserver_request_duration_seconds Response latency distribution in seconds for each verb, dry run value, group, version, resource, subresource, scope and component.

### Affected releases

* x.y
* earlier versions
