### ISSUE TITLE
v56: increased cross-az network traffic following multi-az 00-shared-services

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2173]
### Expected behavior

* As a paas-templates operator
* In order to ensure user-facing quality of service
* I need paas-templates to make sensible use of available network bandwidth across azs (r1, r2, r4)

### Observed behavior
 
* global increased bandwidth usage from v55 preprod to v56 integration
* cross-az traffic from k8s agents to k8s servers (load-balanced without az affinity)

v56 changes increasing network usage:
* 2 k8s servers on r1 -> n servers on r2,r4
* 00-k8s-ha-datastore
* agents -> servers cross-az traffic 

### Possible solutions

* [ ] Improve measurements of cross-az bandwidth consumption: #1510
  * inter regions
      * ntop-ui
  * by namespaces
      * inter namespace
  * ntop_exporter as a daemon set
      * https://github.com/aauren/ntopng-exporter

Emergency approaches to reduce cross-az bandwidth:  
* [ ] Test benefits and side effects effects of stopping instances
    * [ ] on 00-shared-service, stop:
        * [ ] server/ r2 instances
        * [ ] server/ r4 instances 
    * [ ] stop shared-service-r2 (only agents) 
        * [ ] pb with longhorn nodes: will start creating replicas on r4 and streaming data ?
            * [ ] delete large-statefulset
            * [ ] delete longhorn helmrelease 
    * [ ] stop on 00-k8s-ha-datastore 
        * [ ] server/ r2 instance
        * [ ] postgresql r2 replica
            * [ ] WAL S3 backup
            * [ ] fullbackup 
    * DO NOT stop server r1, r4 on 00-k8s-ha-datastore: would break required quorum on r1,r2
* [ ] Confirm/measure expected user-facing impact of 00-shared-services partial unavailability
  * observability for mysql extended (becomes unreacheable)
      * prometheus
  * new mysql-dedicated (single az) instances fails
      * but quota=0
  * migrated mysql-dedicated (single az)  to helm DBO: fail ?

Middle/long terms ways to reduce cross-az bandwidth:
* [ ] don't use r1 intranet proxy from r2 and r4 to reach S3 endpoint  
* [ ] optimize cross-az traffic used for *metrics-based observability*
  * [ ] collect metrics locally (one prometheus instead in each az)
  * [ ] visualize locally (one grafana instance in each az)
  * [ ] trigger alerts locally (deploy alerts to prometheus instance in each az )
  * [ ] route alerts centrally: multi-az alert-manager
  * [ ] more selectively aggregate metrics cross-az
     * [ ] increase scrape times (from 5 to 15 minutes) 
     * [ ] restricted time series 
* [ ] optimize cross-az traffic used for *log-based observability* ?
    * [ ] collect logs locally (one grafana loki in each az)
    * [ ] visualize logs locally (one grafana instance in each az)
    * [ ] compress logs before aggregating them centrally #1970
* [ ] optimize cross-az traffic used for sending data to intranet (backups) #2006

### Affected releases

* 56.0.2
* earlier versions
