### ISSUE TITLE
v56: bad 00-shared-services recovery from network partitions (e.g. vpn r4 or r2 stopped): instabilities, network traffic increase, and k8s inventory data loss

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2174]
### Expected behavior

* As a paas-templates operator 
* In order to 
* I need that network partitions recover without service disruption

### Observed behavior
 
Observed behavior after recover + **cross-az bandwidth limitation (wondershaper at 100 mb per region)**

* large increase in cross-az network bandwidth (100 mb/s)
* 00-shared-services k8s control plane disruptions
   * Haproxy load balancer fronting kine is observing frequent fail overs among kine instances
      * Kine are reporting slow SQL responses from cnpg
      * 00-k8s-ha-datastore k3s servers show etcd errors
   * k8s inventory loss (coab service instance namespaces disappear)
   * Slow k8s api response times (6s to get list of pods)

### Possible fixes

Measure & observe **without restricted bandwidth attempted set up for #2173**
* [ ] reproduce the network partition and recovery

Test integrity of K8s inventory backups
* [ ] measure size of WAL backup
* [ ] restore & use k8s inventory from cnpg backup 

Tune cnpg replication policy to limit k8s inventory data-loss
* [ ] #2119

### Affected releases

* 56.0.2
* earlier versions
