### ISSUE TITLE
Standardize ops automation for analysis and workaround 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2233]
### Expected behavior 

* As a paas-templates operator | paas-templates maintainer
* In order to benefits from diagnostics/workarounds
* I need to able to invoke automated commands, instead of natural language procedures that require
   * context
   * specifics skills

and

* As a paas-templates maintainer
* In order to best share my work when I
   * analyze problems such as 
      * dns
      * ntp
   * identify workarounds 
* I need 
   * conventions/framework to share my work with others as automated code

### Observed behavior

* Many diagnostics are not shared between paas-templates maintainers and paas-templates operators
* Sharing diagnostics as github issues (with proper formatting/automation) 
   * is time consumming
   * requires skills/training
* Diagnostics commands and automations are seldomly shared, and end up on each contributors computers as "private cheat sheets"

The workarounds that documented in issues are currently only examples which need to be adapted on a case by case.

Here is an example of current code snippet found in release notes or workarounds:
```bash
#$ log-bosh -t <root-deployment > -d <deployment_name>
$ log-bosh -t micro -d 00-core-connectivity-k8s
bosh is 
```

When trying to execute this code, here is the result 

```
-bash: $: command not found
Using environment '192.168.10.10' as user 'xxx'

Task 34222030. Done
[...]
```

### Workaround

* 

### Possible fixes

* [ ] Conventions for shell scripts snippets, such as
```bash
# Possibly explain the syntax of the following command 
# by manually crafted comment
# log-bosh -t <root-deployment > -d <deployment_name>
#
# or quoted output
#
# log-bosh -h
# > USAGE:
# >   log-bosh [OPTIONS]
# > 
# > OPTIONS:
# >   --target, -t "bosh target (micro...)"    Bosh director target
# >   --deployment, -d "deployment name"       Bosh deployment name
# >   --uaa, -u 
# > 
log-bosh -t micro -d 00-core-connectivity-k8s
bosh is 
```

See longer example in private security backlog entry 116

* [ ] Shared IDE configuration to reduce cost of authoring shared diagnostics and workaround automation
   * [ ] multiline quoted comment
   * [ ] Test snippet within the IDE (i.e. without copy/paste into bastion)
   * [ ] Productive publication from the IDE (i.e. without copy/paste into the issue)
      * [ ] github issue authoring from the IDE ?
      * [ ] github gists referenced in the issue from the IDE ?

* [ ] For loop conventions (for-each syntax), include support for
   * [ ] Human control/verification
   * [ ] Templating variables within the loop
   * [ ] For each instance group in bosh deployment  
      * [ ] Regexp `agent.*|server.*`
      * [ ] Extract ip addresses 
         * [ ] private ip address
         * [ ] intranet-facing ip address
   * [ ] For each in k8s

* [ ] Documented shell authoring functions/aliases/scripts
   * [ ] environment variables
   * [ ] credhub-get

* [ ] Automated anonymization of security sensitive details
   * [ ] Intranet-facing Ip addresses
   * [ ] Intranet-facing FQDNs
   * [ ] passwords/credentials

* [ ] Support for real-time collaboration on the diagnostic file
   * [ ] ~~etherpad private instance~~ 
   * [ ] hedgedoc private instance
   * [ ] IDE pair programming

* [ ] Support for posting images
   * [ ] Github 
   * [ ] Hedgedoc 
   * [ ] grafana snaphot built-in feature
   * [ ] prometheus snapshot ?

### Affected releases and environments

* affects release: x.y
* affects iaas-type: all | vsphere | openstack
* affects environment: all | integration (openstack) | integration (vsphere) | preprod | prod

<!--
