### ISSUE TITLE
automate authoring of bosh releases versions

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2246]
### Expected behavior 

* As a paas-templates paas-templates author | maintainer
* In order to contribute features/fixes to custom paas-templates bosh releases
* I need automation to 
   * reduce barrier to entry (in terms of tools installation)
   * save effort (in terms of manual commands executed)

and

* As a paas-templates operator
* In order to get up-to-date upstream artefacts
* I need automated bumps of upstream components and bosh release creation #2225

### Observed behavior

* Manual package bump and release creation

### Workaround

* 

### Possible fixes

* [x] Split release between packages and wrapper. See https://github.com/orange-cloudfoundry/k3s-boshrelease/discussions/195

For wrapper releases (e.g. [k3s-wrapper-boshrelease](https://github.com/orange-cloudfoundry/k3s-wrapper-boshrelease)):
* [x] new process for automated bosh release creation https://github.com/orange-cloudfoundry/k3s-wrapper-boshrelease/blob/master/CONTRIBUTING.md
* [x] renovate normally proposes bumps in feature-bumps (no yet need for renovate auto-merge)

For package releases (e.g. [k3s-packages-boshrelease](https://github.com/orange-cloudfoundry/k3s-packages-boshrelease)):
* [x] new automated package bump and bosh release creation. See https://github.com/orange-cloudfoundry/k3s-packages-boshrelease/issues/6
* [x] renovate normally proposes bumps in feature-bumps (no yet need for renovate auto-merge)

### Affected releases and environments

* affects release: 56.1
* affects iaas-type: all | vsphere | openstack
* affects environment: all | integration (openstack) | integration (vsphere) | preprod | prod

<!--
