### ISSUE TITLE
Consistent/regular backup failures

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2291]
### Bug Impact 

* As a marketplace user 
* In order to recover from outages (application outages, or paas-templates-related outages)
* I need that my data are properly backed up

* As a paas-templates operator 
* In order to comply with RPO SLA/SLO
* I need that backup succeed

### Observed behavior

* Regular backup failures 
![image](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/ed3dfec6-3c66-464f-abef-57f8869d0960)

Root causes:
* Some database instances are over quota and shortage of ephemeral storage fail backup
* errors while writing to remote S3 through http proxy 
   * http proxy errors https://github.com/orange-cloudfoundry/paas-templates/issues/2121
      * http proxy shared with high control plane traffic (thanos #1069 and loki #1788)
   * remote S3 potentially delayed/impacted by high high control plane traffic (thanos and loki)

* 

### Workaround

* [ ] Improve alerting to Set different priority for partial cluster backup failure, vs full cluster failure
      * Even through a successful partial cluster backup may still result in lower RPO in case of cluster degraded state (out of sync nodes)

### Possible fixes

* [ ] Increase ephemeral storage to ensure persistent data can be backed up even when reaching out of disk
* [ ] Use a dedicated intranet http proxy service for data plane traffic (service instance backup)
* [ ] Improve availability of http proxy https://github.com/orange-cloudfoundry/paas-templates/issues/2121
* [ ] Reduce control plane usage of S3 (thanos #1069 and loki #1788)
* [ ] Mysql specifics
   * [ ] Enforce quota for mysql dedicated instances to avoid getting out of quota
* [ ] User-facing metrics and alerts for usage over quota for dedicated instances (so that user can optimize/clean-up data/upgrade plan)
* [ ] Ops-facing metrics and alerts for  usage over quota for dedicated instances 
* [ ] #977

* 

### Affected releases and environments

* affects release: 56.0.5
* affects iaas-type: all | vsphere | openstack
* affects environment: all | integration (openstack) | integration (vsphere) | preprod | prod

<!--

**Comment by gberche-orange** [comment]
priorities assigned to highest priority granular issues to be created.
Reminder milestone for epic in v58
