### ISSUE TITLE
Support integ with corporate CMDB and alerting systems

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#339]
### Expected behavior

As a an application team, in order for my corporate CMDB and alerting system to notify me in case my app or service instances are malfunctionning (CF app status is crashed, service instance is reaching service plan quota etc), I need a way to associate by cloudfoundry entities (e.g. org/space/app/service instance) with the identity of my application in my corporate CMDB and alerting system

As a tenant users, in order to integrate all apps in my tenant (org/isolation segment/CF deployment) with my corporate CMDB and alerting system, I need a standard way to be notified of a subset of [CF audit events](https://docs.cloudfoundry.org/running/managing-cf/audit-events.html) including metadata to associate these events with my corporate referential.

### Observed behavior

Some orange entities 
* have extended some service brokers to require cmdb metadata as mandatory params
* have requested developers to add CMDB metadata as application environment variables
* have developped CMDB bridges that query CF API (potentially on multiple CF deployments) to extract app identity from apps and service instances, and reexpose it/export it to corporate CMDB system. Such bridges require `cloudcontroller.admin` permissions.

### Possible implementations

CloudFoundry now supports [meta-data annotations](https://docs.cloudfoundry.org/adminguide/metadata.html) (as key/value pairs) on most entities such as org/space/app. Platform users (org admins, space managers, app developers) can therefore annotate these entity (e.g. app-cmdb-code=1234, slack-alerting=my-app-slack-channel)

Request for propagation of annotations in service brokers is in discussion in https://github.com/openservicebrokerapi/servicebroker/issues/654

A stream of [CF audit events](https://docs.cloudfoundry.org/running/managing-cf/audit-events.html) could be enriched with annotations, and made available for corporate CMDB  in different form:
* a messaging stream (rabbitmq/kafka)
* S3 archives 

### Affected release

Reproduced on version 40.x

 -->

**Comment by gberche-orange** [comment]
Expecting UX based on https://docs.google.com/document/d/1fVO3nA0T5uApN5yWqSZaD3ddZQClCzogeivKxhriLJs/edit option #1 being implemented into [CF CLI epic](https://www.pivotaltracker.com/epic/show/4231034):

This focuses alerting on marketplace services.

```sh
# org managers set default alerting for production internet-facing isolation segment
cf set-annotation isolation-segment "my-corporate-prod-internet-facing-is" "com.orange/send-alerts-to-email=my_default_division_internet_facing_ops_team_mailing_list@mycompany.com"

# org managers set default alerting for production organization
cf set-annotation org "my-corporate-prod-team-or-division" "com.orange/send-alerts-to-email=my_default_division_ops_team_mailing_list@mycompany.com"

# space managers set alerting for a production app space
cf set-annotation space "my-app-prod" "com.orange/send-alerts-to-email=my_app_ops_team_mailing_list@mycompany.com"

# space developers set app-specific alerting for a micro service in a given non-production app space
cf set-annotation app "my-micro-service" "com.orange/send-alerts-to-email=my_dev_and_qa_microservice_team_mailing_list@mycompany.com"

# space developers set service-specific alerting for a service instance in a given non-production app space
cf set-annotation service "my-microservice-mongodb" "com.orange/send-alerts-to-email=my_microservice_mongodb_expert_team_mailing_list@mycompany.com"

# space developers set route specific alerting for a route service instance in a given non-production app space
cf set-annotation route "my-microservice-production-route" "com.orange/send-alerts-to-email=my_security_noc_to_,notify_on_ddos_attacks_mailing_list@mycompany.com"
```

Potentially alerting on application instances could be using the same mechanism: ie. apps that need alerting would be bound to an alerting service instance provisionned from the marketplace. This service instance would therefore leverage the same annotations provided through OSB than other marketplace services (such as data services or route services)

**Comment by gcordierOrange** [comment]
- Add new parameters to command:
  - cf.metadata-enabled (true / false) : active or not the metadata labels
  - filter.metadata (comma separated metatada to get (annotations.foo, labels.foo)
- Add client cf support api v3 for service_instance
- Edit collector for service_instance to query with v3 api

**Comment by gberche-orange** [comment]
CAPI [release 1.108.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.108.0) implemented sending annotations to brokers:
> v3 Send "app_annotations" as part of service instance bindings details
> v3 Send "space_annotations" and "organization_annotations" as part of service instance provisioning, updating and binding details
> v3 Send only non-private annotations associated with the app's space or organization as part of service instance provisioning, updating, and binding details

Cf-deployment v16.11.0 (see bump https://github.com/cloudfoundry/cf-deployment/commit/1b2367f37cea2dffa1ab35d5935c08937096bc72) now includes capi 1.109.0, see bump at https://github.com/cloudfoundry/cf-deployment/commit/357009d4508d99f2fd573eb7b7e8ab088c6afe10

Next steps 
* [ ] bump master-depls/cf to cf-deployment v16.11.0
* [ ] surface CF labels and annotations in osb-cmdb inventory and propagate to service brokers: https://github.com/orange-cloudfoundry/osb-cmdb/issues/108
* [ ] Leverage cf-wall to notify osb client platform users specified as annotations:
   * [ ] Make CF-Wall available to osb-cmdb operators https://github.com/orange-cloudfoundry/paas-templates/issues/24
   * [ ] Enhance CF-Wall to discover email addresses specified as annotations on cf-org, cf-space, cf-service-instance https://github.com/orange-cloudfoundry/cf-wall/issues/13 In the case of osb-cmdb, annotations would be most always specified on service instances

**Comment by gberche-orange** [comment]
Update following exchange with @psycofdj : publicly available Cf-Wall is being deprecated in favor of a closed source cftools suite of microservices designed to integrate CF with Orange IT (CMDB, email alerting, etc). Expressed rationales for deprecating cf-wall:
- set up a cache when querying CF APIs and share this cache among Cf API clients
- support "CF cluster per AZ" pattern instead/in-addition of usual "Multi-az CF cluster"
