### ISSUE TITLE
cache internet resources for airgaped run

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#621]
### Expected behavior
As a platform operator, i expect a smooth run even if internet access is down, with;
- [x] docker registry (sonatype nexus, on jfrog container registry)
- [ ] public git repos, eg (see https://github.com/orange-cloudfoundry/cf-ops-automation/issues/69 )
   - [ ] k8s crd manifest
   - [ ] bosh deployment manifests: mysql-deployment
- [ ] public github release files (eg: docker bosh-cli)
- [x] public helm charts repo (vmware harbor or jfrog container registry)
- [ ] bosh terraform plugins

### Observed behavior
as of v43, all internet access from platform components are:   
- downloaded with a http proxy (micro-depls/internet-proxy)
- cached on the fly. Eg, micro-depls/nexus ensure a docker image caching for nexus, docker and k8S components
- cached with concourse pipeline (eg: COA declared bosh release, with upload team)

Even proxyied, runtime internet access are still vulnerable to
- internet access layer failure
- internet resources failure (eg : 2 dockerhub incidents in 2019)

Also, control plane cf-apps (OSB brokers) implemented with cf should leverage cached-buildpacks

### Implementation steps
* [ ] vendor remote git repos using vendir
* [ ] Publish orange-cloudfoundry jar artefact as OCI image bundle during CI/CD release process. 
   * Possibly using native CI/CD workflows, or  https://github.com/vmware-tanzu/carvel-imgpkg
* [ ] Update associated cf-app pre-cf-push to replace curl with call to [vendir](https://carvel.dev/vendir/docs/latest/vendir-spec/) using the `image` syntax and `includePaths` to fetch oci image from paas-template jcr registry (with caching) and extract files in local filesystem

**Comment by poblin-orange** [comment]
TODO:
- [ ] github repo. git "mirror feature" ? replace git submodule by vendoring tool ?
- [ ] clis (bosh/credhub) => replicate in micro-depls/minio ?

**Comment by gberche-orange** [comment]
Discussion during backlog review on how to extend OCI caching to preq CLIs (bosh, credhub, svcat, ...)
* leverage existing "all-in-one/monolith" docker image such as docker-bosh-cli
* leverage 
   * fetched explicitly using vendir
   * mount in k8s pod as volume

**Comment by gberche-orange** [comment]
Reopening as only partially addressed in https://github.com/orange-cloudfoundry/paas-templates-private/pull/2046
