### ISSUE TITLE
(spike) evaluate github private repo

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#766]
### Expected behavior
As paas-templates author, using integration environement, id like to use a single tooling for release management

### Observed behavior
Release management is split:
- issues on github
- merge request on private gitlab
- all releases note detailled content is manually edited from PR when merged

### Spike content
- [x] add a private repo in orange-cloudfoundry org
- [x] git clone mirror + push all branches on github
- [x] switch COA concourse to use github instead of gitlab for paas-templates.
- [ ] assess performance / scalaibility

**Comment by poblin-orange** [comment]
done as of v46
