### ISSUE TITLE
Osb-cmdb smoke tests to include K8S client

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#794]
### Expected behavior

* As a paas-templates operator 
* In order to be confident that K8S svcat clients properly consome osb-cmdb (see #955 as a sample production issue)
* I need the osb-cmdb smoke tests to invoke svcat 

### Observed behavior

osb-cmdb smoke tests only invoke CF CLI 

Depends on #751 

### Implementation steps

* [ ] Add automated test coverage
   * [ ] using paas-templates smoke test 
      * [ ] add basic coverage for svcat client
         * [x] Register osb-cmdb-0 
            * [x] create namespace osb-cmdb-0-smoke-test
            * [x] register osb-cmdb-0 in namespace
         * [x] provision instance
         * [ ] bind instance. 
            * [ ] Fetch credentials from secrets 
            * [ ] deploy probe app with kpack/paketo in k8s ?
            * [ ] deploy probe app within master-depls/cf and a cups using svcat-generated secret ?
         * [ ] deprovision instance
      * [ ] add plan update ?
   * [ ] using osb-cmdb acceptance tests
      * [ ] direct osb api call to osb-cmdb for service instance params update without providing a plan id
      * [ ] use K8S service catalog
         * [ ] using java K8S client (such as https://github.com/fabric8io/kubernetes-client )
            * [ ] connect to https://k8s-serv-api.internal.paas
               * [ ] from concourse
               * [ ] from desktop machine
                  * [ ] using ssh port forwarding + local DNS /etc/hosts
                  * [ ] using intranet K8S cluster
                  * [ ] using HTTP2 traefik route on intranet
                  * [ ] using VPN for dev only

### Affected releases

* 46.x

**Comment by poblin-orange** [comment]
sample apps will be in k8s-master, in a dedicated namespace  (/product)
