### ISSUE TITLE
support new dedicated mysql instances metrics lookup through grafana anonymous dashboard

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#797]
### Expected behavior

As a marketplace user
* In order to monitor/troubleshoot slow applications using a newly provisioned dedicated mysql
* I need to lookup performance and capacity metrics in my mysql dedicated cluster in a self-service way

### Observed behavior
 
* dedicated instances grafana dashboard are only [partly] accessible to service operators (#666 #770)

### Affected releases

* v46.x

### implementation steps

Planned architecture (see https://miro.com/app/board/o9J_krEBr-4=/ )
![image](https://user-images.githubusercontent.com/4748380/91453271-d0375800-e87f-11ea-9ea3-6b54044e89db.png)

* [ ] (optional) osb-cmdb dashboard aggregator webpage https://github.com/orange-cloudfoundry/osb-cmdb/issues/48
* [ ] update mysql model to include low footprint prometheus & grafana processes collocated with broker vm and exposed on a route prefixed with brokered service instance guid. See https://github.com/orange-cloudfoundry/osb-cmdb#osb-api-extension-used-with-backing-service-brokers the x-osb-cmdb param includes the `brokered_service_instance_guid`
* [ ] configure coab broker to return mysql dashboard with brokered service instance guid, see https://github.com/orange-cloudfoundry/cf-ops-automation-broker/blob/5ecf354b3ad04773311d15c4fba297a229c1ccdb/cf-ops-automation-bosh-broker/src/test/resources/application.properties#L93-L97
