### ISSUE TITLE
Automated updates for upstream dependencies 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#869]
### Expected behavior

* As a paas-templates maintainer
* In order to avoid using deprecated or vulnerable dependencies (docker images, bosh deployment repos such as cf-deployment, upstream java libraries, 
* I need to receive PRs with version bumps from [github dependabot](https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically)

Dependabot [currently supports](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem) the following dependencies managed by paas-templates or upstream projects
   * Docker: docker (from images) -> COA docker images from Docker files (see [related dependabot specs](https://github.com/dependabot/dependabot-core/blob/main/docker/spec/dependabot/docker/file_parser_spec.rb))
   * git submodule: gitsubmodule -> bosh deployment repos in paas-templates. Currently creates a PR for every commit, see https://github.com/dependabot/dependabot-core/issues/2192 for sticking to releases
   * Terraform: terraform. Currently supports bumping [terraform remote modules](https://www.terraform.io/docs/modules/index.html) (see sample [tf file](https://github.com/dependabot/dependabot-core/blob/main/terraform/spec/fixtures/config_files/git_tags.tf) and [associated tests](https://github.com/dependabot/dependabot-core/blob/f3b563823ac79d152be2250558d5af40c1f85578/terraform/spec/dependabot/terraform/file_parser_spec.rb#L63-L99))
   * Java -> osb-cmdb, coab
      * Gradle: gradle
      * Maven: maven
   * Bundler: bundler (ruby)
   * Cargo: cargo
   * Composer: composer
   * Elm: elm
   * GitHub Actions: github-actions
   * Go modules: gomod
   * Mix: mix
   * npm: npm
   * NuGet: nuget
   * pip: pip

Other dependencies not yet supported by dependabot:
* helm charts, see https://github.com/dependabot/dependabot-core/issues/1744

According to [github pricing](https://github.com/pricing) dependabot is also available to free accounts (public and limited private repo)

![image](https://user-images.githubusercontent.com/4748380/91285200-30999d00-e78d-11ea-9c38-cbeb5a977c6d.png)

### Observed behavior
 
Most dependent packages PR are currently manually crafted

### Affected releases

* 47.0.3

### Implementation steps

* [x] Enable dependabot for paas-templates-private repo (docker images and git submodules). https://github.com/orange-cloudfoundry/paas-templates-private/pull/235
* [ ] Enable dependabot for upstream projects
   * [x] Osb-cmdb
   * [x] COAB
   * [ ] COA ruby (bundler)
   * [ ] COA docker images
   * [ ] Docker bosh cli: FROM image (currently unversionned)

**Comment by gberche-orange** [comment]
Note that dependabot support for docker files does not yet parses wget to github releases or apt-get, see related suggested improvements:
* https://github.com/dependabot/dependabot-core/issues/2129 (apt-get)
* https://github.com/dependabot/dependabot-core/issues/2483 (wget/curl )

Similarly, support for K8S spec files was requested into https://github.com/dependabot/dependabot-core/issues/2217

**Comment by gberche-orange** [comment]
Manual workaround for gitsubmodules bumps that don't bump to tags https://github.com/dependabot/dependabot-core/issues/2192

1. open list of tags in the associated repo: open the repo, and browse to releases and tags. E.g. https://github.com/cloudfoundry/cf-deployment/tags
![image](https://user-images.githubusercontent.com/4748380/93586935-61927980-f9a9-11ea-8a68-bc201e550486.png)
![image](https://user-images.githubusercontent.com/4748380/93587012-7e2eb180-f9a9-11ea-85c9-3d184ceb7852.png)
1. expand list of commits
![image](https://user-images.githubusercontent.com/4748380/93586476-a669e080-f9a8-11ea-9680-61bac396359b.png)
1. compare both list for matches

**Comment by gberche-orange** [comment]
Lacking consensus on 
* bump for docker-bosh cli
* COA bumps: need to review added-value for ruby/docker bumps

**Comment by poblin-orange** [comment]
closing as PR generated from dependabot not used

**Comment by gberche-orange** [comment]
Reopening following changes in OSS ecosystem:

The dependabot approach had limitations, in particular the dependabot [not supporting new ecosystems since december 2020](https://github.com/dependabot/dependabot-core/blob/main/CONTRIBUTING.md#contributing-new-ecosystems) in particular helm charts in fluxcd `HelmRelease` CRs, see https://github.com/dependabot/dependabot-core/issues/1744

Alternative approaches are now available:
- the renovatebot: https://github.com/renovatebot/renovate
   - supports custom dependencies formats (called "managers"): https://docs.renovatebot.com/configuration-options/#regexmanagers
- https://github.com/updatecli/updatecli
   - specifically designed to bump custom dependencies "formats" (called targets) such as coa files or HelmRelease
   - supports opening a GH PR https://www.updatecli.io/docs/plugins/pullrequest/github/
   - built-in github action integration https://www.updatecli.io/docs/automate/github_action/
   - example usage for bumping dependencies within helm charts https://blog.promaton.com/how-to-set-up-automated-helm-chart-upgrades-e292192a9aad

Renovatebot seems to have a wider ecosystem and community and richer feature set:
- PR content is richer: age, adoption, confidence, release note. See sample at https://github.com/gberche-orange/renovate-bot-tutorial/pull/3

**Comment by gberche-orange** [comment]
Alternatives for fluxcd2 HelmRelease support in renovatebot:
* https://docs.renovatebot.com/modules/manager/flux/
  * [x] configure path to opt-in out flux kustomization files containing `HelmRelease`
   * need refactoring our HelmRepository structure
      * [ ] prototype default internet reachable HelmRepo in git
         * [ ] with a runtime kyverno fix to reach internal jcr
         * [ ] with a deploy-time kustomization overlay ignored by renovatebox
   * tune the PR submission/tests/review/ process.
      * PR naming, granularity and rate
      * PR review & test: 
         * manual merge into feature-bump branch ?
            * with manual copy of markdown content ?
         * manual test review and tracking
* https://docs.renovatebot.com/modules/manager/regex/
