### ISSUE TITLE
support existing dedicated mysql instances metrics lookup through grafana anonymous dashboard 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#870]
### Expected behavior

As a marketplace user
* In order to monitor/troubleshoot slow applications using a previously dedicated mysql
* I need to lookup performance and capacity metrics in my mysql dedicated cluster in a self-service way

### Observed behavior

* coab instances created prior to v48 don't return a dashboard url
* instances created prior to v47 don't have coab-vars.yml metadata provided in [osb-cmdb 1.0](https://github.com/orange-cloudfoundry/osb-cmdb/releases/tag/v1.0.0) through https://github.com/orange-cloudfoundry/osb-cmdb/issues/15 to expose brokered service instance guid
 
### Affected releases

* 47.0.3
* earlier versions

### Implementation steps
* [x] grafana support for new instances in #797
* [ ] coab to support dashboard url refresh to fetch grafana url https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/278
* [ ] coab to trigger model updates on `cf update-service --upgrade`, so that brokered service instance guid get available in coab-vars.yml, for use in grafana deployment FQDN, see https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/40
